spring.application.name=demo
# Configuração do Banco de Dados em Memória (H2)
spring.datasource.url=jdbc:h2:mem:terapiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra no terminal o que o Java está fazendo no banco
spring.jpa.show-sql=true

# Habilita uma tela no navegador para a gente ver a "planilha" de usuários
spring.h2.console.enable=true
spring.h2.console.path=/h2-console